"""Unit tests for the PII redactor (regex stage).

Targets per PLAN §10.2 measurable bar:
    Aadhaar / Mobile / PAN: precision ≥ 0.99, recall ≥ 0.95.

These tests cover the structural correctness on hand-crafted positive + negative
examples. The full release gate (200-doc hand-labeled set) is a separate
workstream and lives in `tests/pii_eval/` (not yet built).
"""
from __future__ import annotations

import pytest

from ingest.normalize.redact import (
    CaseType,
    PIIType,
    detect_case_type,
    redact,
    verhoeff_valid,
)

# --- Aadhaar / Verhoeff ------------------------------------------------------

# Synthetic Verhoeff-valid Aadhaars (NOT real numbers). Generated by appending
# the unique checksum digit to an 11-digit base — see `make_valid_aadhaar`
# below if you need more test vectors.
VALID_AADHAARS = [
    "234123412346",
    "499118600081",
    "835417410425",
    "123456789010",
]
# Verhoeff-failing 12-digit numbers. NOTE: 999999999999 *does* pass Verhoeff
# (coincidence of the dihedral table), so it's not in this list.
INVALID_AADHAARS = [
    "123456789012",
    "000000000000",
    "111111111111",
    "555555555555",
]


def make_valid_aadhaar(eleven_digit_base: str) -> str:
    """Append the unique Verhoeff checksum digit. Test helper."""
    for last in "0123456789":
        candidate = eleven_digit_base + last
        if verhoeff_valid(candidate):
            return candidate
    raise AssertionError(f"no valid Verhoeff digit for base {eleven_digit_base}")


class TestVerhoeff:
    @pytest.mark.parametrize("number", VALID_AADHAARS)
    def test_known_valid_passes(self, number: str) -> None:
        assert verhoeff_valid(number) is True

    @pytest.mark.parametrize("number", INVALID_AADHAARS)
    def test_obviously_invalid_fails(self, number: str) -> None:
        assert verhoeff_valid(number) is False

    def test_non_digit_fails(self) -> None:
        assert verhoeff_valid("12345678901a") is False

    def test_empty_fails(self) -> None:
        assert verhoeff_valid("") is False


# --- Aadhaar redaction -------------------------------------------------------

class TestAadhaarRedaction:
    def test_redacts_valid_aadhaar_unformatted(self) -> None:
        text = f"His Aadhaar number is {VALID_AADHAARS[0]} as stated."
        result = redact(text)
        assert "[AADHAAR REDACTED]" in result.text
        assert VALID_AADHAARS[0] not in result.text
        assert len([h for h in result.hits if h.pii_type == PIIType.AADHAAR and h.confidence > 0]) == 1

    def test_redacts_valid_aadhaar_with_spaces(self) -> None:
        a = VALID_AADHAARS[1]
        text = f"Aadhaar No: {a[:4]} {a[4:8]} {a[8:]}"
        result = redact(text)
        assert "[AADHAAR REDACTED]" in result.text

    def test_redacts_valid_aadhaar_with_hyphens(self) -> None:
        a = VALID_AADHAARS[2]
        text = f"UIDAI: {a[:4]}-{a[4:8]}-{a[8:]}"
        result = redact(text)
        assert "[AADHAAR REDACTED]" in result.text

    def test_does_not_redact_invalid_but_flags_suspicious(self) -> None:
        # 12-digit number that doesn't pass Verhoeff — leave in place,
        # but mark the chunk as suspicious for quarantine.
        text = f"Reference no. {INVALID_AADHAARS[0]} in the order."
        result = redact(text)
        assert INVALID_AADHAARS[0] in result.text  # not redacted
        assert result.suspicious is True            # but flagged

    def test_does_not_redact_year_runs(self) -> None:
        # 4-digit years adjacent to a 4-digit case number shouldn't trigger
        text = "Case No. 1234 of 2024 was decided on 5678 lines of the order."
        result = redact(text)
        # No 12-digit run, so no Aadhaar hit
        aadhaar_hits = [h for h in result.hits if h.pii_type == PIIType.AADHAAR]
        assert aadhaar_hits == []

    def test_multiple_aadhaars_all_redacted(self) -> None:
        text = f"Petitioner: {VALID_AADHAARS[0]}, Respondent: {VALID_AADHAARS[1]}."
        result = redact(text)
        assert result.text.count("[AADHAAR REDACTED]") == 2
        assert VALID_AADHAARS[0] not in result.text
        assert VALID_AADHAARS[1] not in result.text


# --- Mobile ------------------------------------------------------------------

class TestMobileRedaction:
    @pytest.mark.parametrize("mobile", ["9876543210", "8123456789", "7000000001", "6543210987"])
    def test_redacts_indian_mobile(self, mobile: str) -> None:
        text = f"Contact: {mobile} for any queries."
        result = redact(text)
        assert "[MOBILE REDACTED]" in result.text
        assert mobile not in result.text

    @pytest.mark.parametrize("mobile,prefix", [
        ("9876543210", "+91"),
        ("9876543210", "+91 "),
        ("9876543210", "91-"),
        ("9876543210", "0"),
    ])
    def test_redacts_with_prefix(self, mobile: str, prefix: str) -> None:
        text = f"Call {prefix}{mobile} for support."
        result = redact(text)
        assert "[MOBILE REDACTED]" in result.text

    @pytest.mark.parametrize("non_mobile", ["1234567890", "5876543210", "0987654321"])
    def test_does_not_redact_invalid_start(self, non_mobile: str) -> None:
        # First digit must be 6-9; first digit 1/2/3/4/5/0 is invalid.
        text = f"Number {non_mobile} is not a mobile."
        result = redact(text)
        mobile_hits = [h for h in result.hits if h.pii_type == PIIType.MOBILE]
        assert mobile_hits == []

    def test_does_not_redact_section_number_ranges(self) -> None:
        # Court orders often have stuff like "section 9876 of XYZ Act"
        # We accept some false positives here — recall over precision.
        # This test documents the known limitation.
        text = "Order of 8765432109 lines was passed."  # 10 digits starting with 8
        result = redact(text)
        mobile_hits = [h for h in result.hits if h.pii_type == PIIType.MOBILE]
        # Known FP — we redact. This is acceptable per §10.2 (precision target
        # applies to the full pipeline including context heuristics, not the
        # raw regex stage alone).
        assert len(mobile_hits) == 1


# --- PAN ---------------------------------------------------------------------

class TestPANRedaction:
    @pytest.mark.parametrize("pan", ["AAAPL1234C", "BBBFL9999A", "ZZZHJ0000Z"])
    def test_redacts_valid_pan_structure(self, pan: str) -> None:
        text = f"PAN: {pan}."
        result = redact(text)
        assert "[PAN REDACTED]" in result.text
        assert pan not in result.text

    def test_does_not_redact_invalid_entity_letter(self) -> None:
        # 4th letter must be in PFCHATBLJGE. 'X' is not.
        text = "Case ABCDX1234E is pending."
        result = redact(text)
        pan_hits = [h for h in result.hits if h.pii_type == PIIType.PAN]
        assert pan_hits == []
        assert "ABCDX1234E" in result.text


# --- Email -------------------------------------------------------------------

def test_redacts_email() -> None:
    text = "Reach out at counsel@example.com for clarification."
    result = redact(text)
    assert "[EMAIL REDACTED]" in result.text
    assert "counsel@example.com" not in result.text


# --- Bank account ------------------------------------------------------------

class TestBankAccountRedaction:
    def test_redacts_long_number_near_keyword(self) -> None:
        text = "Account No: 12345678901234 holding the disputed deposit."
        result = redact(text)
        assert "[BANK A/C REDACTED]" in result.text

    def test_does_not_redact_long_number_without_keyword(self) -> None:
        # Without a bank keyword nearby, we don't redact long digit runs
        # (too many false positives — case numbers, transaction IDs, etc.).
        text = "Order page 12345678901234 of the file."
        result = redact(text)
        bank_hits = [h for h in result.hits if h.pii_type == PIIType.BANK_AC]
        assert bank_hits == []


# --- Case-type detection -----------------------------------------------------

class TestCaseTypeDetection:
    @pytest.mark.parametrize("header,expected", [
        ("This is a petition under the POCSO Act, 2012 ...", CaseType.POCSO),
        ("In the matter of matrimonial cause filed under the Hindu Marriage Act...", CaseType.MATRIMONIAL),
        ("Petition under the Juvenile Justice Act for a child in conflict with law...", CaseType.JUVENILE),
        ("Charge under the NDPS Act for possession ...", CaseType.NDPS_MINOR),
        ("Civil suit for recovery of money under Order VII Rule 11 CPC ...", CaseType.STANDARD),
    ])
    def test_detect(self, header: str, expected: CaseType) -> None:
        assert detect_case_type(header) == expected


# --- Integration -------------------------------------------------------------

def test_full_pipeline_pocso_doc() -> None:
    text = (
        "This is a petition under the POCSO Act, 2012. "
        f"The complainant's Aadhaar is {VALID_AADHAARS[0]} and mobile is 9876543210. "
        "PAN: AAAPL1234C, A/c No. 12345678901."
    )
    result = redact(text)
    assert result.case_type == CaseType.POCSO
    assert "[AADHAAR REDACTED]" in result.text
    assert "[MOBILE REDACTED]" in result.text
    assert "[PAN REDACTED]" in result.text
    assert "[BANK A/C REDACTED]" in result.text
    # No raw PII tokens leak through
    for hit in result.hits:
        if hit.confidence > 0:
            assert hit.text not in result.text


def test_no_pii_no_change() -> None:
    text = (
        "The petition was heard at length. The court considered the submissions "
        "of both sides and reserved judgment for further hearing."
    )
    result = redact(text)
    assert result.text == text
    assert result.hits == []
    assert result.suspicious is False
    assert result.case_type == CaseType.STANDARD


# --- DB sanitization --------------------------------------------------------

from ingest.normalize.redact import sanitize_for_db


class TestSanitizeForDb:
    """PyMuPDF can emit NULL bytes from binary PDF glyphs. Postgres rejects
    them. The redactor must strip them before chunking.
    """

    def test_strips_null_bytes(self) -> None:
        text = "Hello\x00 world\x00 with nulls"
        out = sanitize_for_db(text)
        assert "\x00" not in out
        assert out == "Hello world with nulls"

    def test_preserves_normal_text(self) -> None:
        text = "Section 1.\nShort title, extent and commencement.\n(1) This Act…"
        assert sanitize_for_db(text) == text

    def test_preserves_tabs_and_newlines(self) -> None:
        text = "line1\tcol2\nline3\r\nline4"
        assert sanitize_for_db(text) == text

    def test_strips_other_c0_controls(self) -> None:
        # \x01 is SOH; should be replaced with space
        text = "abc\x01def\x02ghi"
        out = sanitize_for_db(text)
        assert "\x01" not in out
        assert "\x02" not in out
        assert "abc def ghi" == out

    def test_redact_pipeline_sanitizes(self) -> None:
        # The redact() entry point should pass through sanitize
        from ingest.normalize.redact import redact
        text = "Patient ID: 234123412346 \x00 unsupported byte here"
        result = redact(text)
        assert "\x00" not in result.text
        # And the PII should still be detected
        assert "[AADHAAR REDACTED]" in result.text
